.TH "ConnectionHandler" 3 "Mon Jul 27 2015" "Version 0" "MWAC Interface Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectionHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectionHandler\fP (const \fBConnectionHandler\fP &orig)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MWAC Interface Library from the source code\&.
