.TH "File.h" 3 "Mon Jul 27 2015" "Version 0" "MWAC Interface Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File.h \- Abstract base class for files used as interfaces to the MWA Correlator\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class for files used as interfaces to the MWA Correlator\&. 


.PP
\fBAuthor:\fP
.RS 4
: Stephen Ord 
.RE
.PP
\fBDate:\fP
.RS 4
22 July 2015, 9:33 PM
.RE
.PP
This library may support multiple interfaces that I am essentially thinking of as 'files' though they are likely to be mostly socket connections\&. Keeping the interface file based may allow some extension and generalisation outside the MWA\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for MWAC Interface Library from the source code\&.
