.TH "File" 3 "Mon Jul 27 2015" "Version 0" "MWAC Interface Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFile\fP ()"
.br
.RI "\fISimple constructor\&. \fP"
.ti -1c
.RI "\fBFile\fP (const \fBFile\fP &orig)"
.br
.RI "\fISimple destructor\&. \fP"
.ti -1c
.RI "virtual int \fBinitialise\fP (int fd)=0"
.br
.RI "\fIpure virtual initialiser \fP"
.ti -1c
.RI "virtual \fB~File\fP ()"
.br
.RI "\fIdestructor \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual int File::initialise (int fd)\fC [pure virtual]\fP"

.PP
pure virtual initialiser 
.PP
\fBParameters:\fP
.RS 4
\fIfd\fP is a file descriptor 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for MWAC Interface Library from the source code\&.
