.TH "vdif_header" 3 "Mon Jul 27 2015" "Version 0" "MWAC Interface Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vdif_header \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBseconds\fP: 30"
.br
.ti -1c
.RI "uint32_t \fBlegacymode\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBinvalid\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBframe\fP: 24"
.br
.ti -1c
.RI "uint32_t \fBepoch\fP: 6"
.br
.ti -1c
.RI "uint32_t \fBunassigned\fP: 2"
.br
.ti -1c
.RI "uint32_t \fBframelength8\fP: 24"
.br
.ti -1c
.RI "uint32_t \fBnchan\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBversion\fP: 3"
.br
.ti -1c
.RI "uint32_t \fBstationid\fP: 16"
.br
.ti -1c
.RI "uint32_t \fBthreadid\fP: 10"
.br
.ti -1c
.RI "uint32_t \fBnbits\fP: 5"
.br
.ti -1c
.RI "uint32_t \fBiscomplex\fP: 1"
.br
.ti -1c
.RI "uint32_t \fBeversion\fP: 8"
.br
.ti -1c
.RI "uint32_t \fBextended1\fP: 24"
.br
.ti -1c
.RI "uint32_t \fBextended2\fP"
.br
.ti -1c
.RI "uint32_t \fBextended3\fP"
.br
.ti -1c
.RI "uint32_t \fBextdended4\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for MWAC Interface Library from the source code\&.
